os: linux
language: minimal

services:
  - docker

before_deploy:
  - docker pull squidfunk/mkdocs-material
  - git branch gh-pages
  - cp README.md docs/index.md
  - mkdir site
  - docker run -ti -v "$(pwd)":/docs squidfunk/mkdocs-material build --clean

deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  local_dir: site
  keep_history: true
  verbose: true
  on:
    branch: master

