site_name: 'Pen my notes'
site_description: 'Notes about my learnings and cheatsheets'
site_author: 'Alex Ho'
site_url: 'https://aluxh.github.io/pen-my-notes/'
repo_name: 'GitHub'
repo_url: 'https://github.com/aluxh/pen-my-notes'

theme: 
  name: material
  feature:
    tabs: true
  markdown_extensions:
    - toc:
        permalink: true
